### ISSUE TITLE
no language information present in transcript/captions

### ISSUE THREAD

**Issue by igorshevach** [verbit-ai/verbit-streaming-python-sdk#14]
https://github.com/verbit-ai/verbit-streaming-python-sdk/blob/main/examples/responses/schema.md
it would be desirable if an utterance of specific speaker be tied to a language used.

**Comment by roman-verbit-ai** [comment]
@igorshevach We currently do not provide automatic language identification via this service.
Are you using this SDK?

**Comment by igorshevach** [comment]
thanks
